name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 170.254.78.193
          port: 4851
          username: invictus
          key: ${{ secrets.DEPLOY_ACTIONS }}
          script: |
            cd ~/desenvolvimento/faculdade/farmer-s_companion
            git pull origin main
            docker compose up -d --build

      - name: Notify Discord - Success
        if: success()
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1486735502097776685/fNdSBU-GmPCY2wRLqGcprPRyir5HvNih0HxfSJffGjF-dDbJWT08M_KTVOMoHSpMdWri
        run: |
          MESSAGE="✅ Deploy realizado com sucesso\nO deploy do ${{ github.event.repository.name }} foi concluído com sucesso.\n\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nAutor: ${{ github.actor }}"
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"embeds\": \"${MESSAGE//$'\n'/\\n}\"}" \
            "$DISCORD_WEBHOOK_URL"

      - name: Notify Discord - Failure
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1486735502097776685/fNdSBU-GmPCY2wRLqGcprPRyir5HvNih0HxfSJffGjF-dDbJWT08M_KTVOMoHSpMdWri
        run: |
          MESSAGE="❌ Falha no deploy\nO deploy do ${{ github.event.repository.name }} falhou.\n\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nAutor: ${{ github.actor }}"
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"embeds\": \"${MESSAGE//$'\n'/\\n}\"}" \
            "$DISCORD_WEBHOOK_URL"